import { AdCampaign, SupportTicket, SyncChannel, TrackedCompetitor } from './types';

export const INITIAL_CAMPAIGNS: AdCampaign[] = [
  {
    id: 'camp-101',
    name: 'Advantage+ Conversions - Smartwatch Pro',
    platform: 'Meta Ads',
    status: 'active',
    spend: 14200,
    revenue: 58900,
    impressions: 485000,
    clicks: 12400,
    purchases: 236,
    roas: 4.15,
    cpa: 60.17,
    ctr: 2.56,
    cpc: 1.15,
    aiVerdict: 'scale',
    recommendation: '4.15x ROAS ile yüksek getiri. Günlük bütçe %20 artırılabilir.',
  },
  {
    id: 'camp-102',
    name: 'Google PMax - Ana Katalog',
    platform: 'Google Ads',
    status: 'active',
    spend: 18500,
    revenue: 61050,
    impressions: 310000,
    clicks: 9800,
    purchases: 198,
    roas: 3.30,
    cpa: 93.43,
    ctr: 3.16,
    cpc: 1.88,
    aiVerdict: 'healthy',
    recommendation: 'Dengeli performans. Negatif anahtar kelime optimizasyonu yapılabilir.',
  },
];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'TCK-8821',
    customerName: 'Ahmet Yılmaz',
    email: 'ahmet.y@example.com',
    orderNumber: '#SV-94821',
    topic: 'Order Status',
    status: 'Open',
    sentiment: 'neutral',
    lastMessage: 'Siparişim ne zaman kargoya verilir?',
    aiSuggestedReply: 'Merhaba Ahmet Bey, #SV-94821 numaralı siparişiniz hazırlanmıştır.',
    createdAt: '10 dk önce',
  },
];

export const INITIAL_CHANNELS: SyncChannel[] = [
  {
    id: 'ch-shopify',
    name: 'Vision Store',
    type: 'Shopify',
    logo: 'Shopify',
    status: 'connected',
    totalProducts: 480,
    syncedCount: 480,
    failedCount: 0,
    lastSyncAt: '2 dk önce',
    autoSyncInterval: 'Real-time (Webhook)',
  },
  {
    id: 'ch-trendyol',
    name: 'Trendyol Mağaza',
    type: 'Trendyol',
    logo: 'Trendyol',
    status: 'connected',
    totalProducts: 480,
    syncedCount: 476,
    failedCount: 4,
    lastSyncAt: '5 dk önce',
    autoSyncInterval: '15 Dakikada Bir',
  },
  {
    id: 'ch-hepsiburada',
    name: 'Hepsiburada Satıcı Paneli',
    type: 'Hepsiburada',
    logo: 'Hepsiburada',
    status: 'connected',
    totalProducts: 480,
    syncedCount: 480,
    failedCount: 0,
    lastSyncAt: '12 dk önce',
    autoSyncInterval: '30 Dakikada Bir',
  },
  {
    id: 'ch-amazon',
    name: 'Amazon TR',
    type: 'Amazon',
    logo: 'Amazon',
    status: 'connected',
    totalProducts: 320,
    syncedCount: 318,
    failedCount: 2,
    lastSyncAt: '20 dk önce',
    autoSyncInterval: '1 Saatte Bir',
  },
];

export const INITIAL_COMPETITORS: TrackedCompetitor[] = [
  {
    id: 'comp-1',
    productName: 'Shaz Vision Ultra Smartwatch Series 5',
    competitorName: 'TechStore Mega',
    platform: 'Trendyol',
    ourPrice: 2499,
    competitorPrice: 2799,
    priceDifference: -10.7,
    status: 'lower',
    trendVelocity: 'stable',
    lastChecked: '4 dk önce',
    url: 'https://trendyol.com/example-item-1',
  },
];
